function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t199_showMenu(recid){var el=$('#rec'+recid);el.find('.t199__js__menu').each(function(){var $toggler=el.find('.t199__js__menu-toggler'),$menu=$(this),$body=$('body'),CLASS_MENU='t199__is__menu';$menu.find('.t199__menu-item').each(function(){var curUrl=$(this).attr('href');if(typeof curUrl!='undefined'&&curUrl.indexOf('#')>-1&&curUrl.substring(0,9)!='#submenu:'){$(this).on('click',function(e){$body.removeClass(CLASS_MENU)})}});$menu.find('.t199__menu-item-wrap .t-menusub__link-item').each(function(){var curUrl=$(this).attr('href');$(this).on('click',function(e){$body.removeClass(CLASS_MENU)})});$toggler.on('click',function(e){e.stopPropagation();e.preventDefault();$body.toggleClass(CLASS_MENU)});$(document).on('click',function(e){var clickedInsideMenu=$(e.target).hasClass('t199__js__menu')||$(e.target).parents('.t199__js__menu').length>0;if(!clickedInsideMenu){$body.removeClass(CLASS_MENU)}})});$('.t199__mmenu').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t199__is__menu')})}
function t199_positionHeader(recid){var el=$('#rec'+recid);var $header=el.find('.t199__js__header'),isScrolling=!1,CLASS_ACTIVE='t199__is__active';function updateHeader(){isScrolling=!0;if($(window).scrollTop()>0)$header.addClass(CLASS_ACTIVE);else $header.removeClass(CLASS_ACTIVE)}
setInterval(function(){if(isScrolling){isScrolling=!1}},100);$(window).on('scroll',updateHeader);updateHeader()}
function t199_setPath(pageid){}
function t199_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$(".t199__menu a[href='"+url+"']").addClass('t-active');$(".t199__menu a[href='"+url+"/']").addClass('t-active');$(".t199__menu a[href='"+pathname+"']").addClass('t-active');$(".t199__menu a[href='/"+pathname+"']").addClass('t-active');$(".t199__menu a[href='"+pathname+"/']").addClass('t-active');$(".t199__menu a[href='/"+pathname+"/']").addClass('t-active')}
function t199_checkAnchorLinks(recid){if($(window).width()>=960){var t199_navLinks=$('#rec'+recid+" .t-menu__link-item:not(.tooltipstered)[href*='#']");if(t199_navLinks.length>0){t199_catchScroll(t199_navLinks)}}}
function t199_catchScroll(t199_navLinks){var t199_clickedSectionId=null,t199_sections=new Array(),t199_sectionIdTonavigationLink=[],t199_interval=100,t199_lastCall,t199_timeoutId;t199_navLinks=$(t199_navLinks.get().reverse());t199_navLinks.each(function(){var t199_cursection=t199_getSectionByHref($(this));if(typeof t199_cursection.attr('id')!='undefined'){t199_sections.push(t199_cursection)}
t199_sectionIdTonavigationLink[t199_cursection.attr('id')]=$(this)});t199_updateSectionsOffsets(t199_sections);$(window).bind('resize',t_throttle(function(){t199_updateSectionsOffsets(t199_sections)},200));$('.t199').bind('displayChanged',function(){t199_updateSectionsOffsets(t199_sections)});setInterval(function(){t199_updateSectionsOffsets(t199_sections)},5000);t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId);t199_navLinks.click(function(){if(!$(this).hasClass('tooltipstered')){t199_navLinks.removeClass('t-active');t199_sectionIdTonavigationLink[t199_getSectionByHref($(this)).attr('id')].addClass('t-active');t199_clickedSectionId=t199_getSectionByHref($(this)).attr('id')}});$(window).scroll(function(){var t199_now=new Date().getTime();if(t199_lastCall&&t199_now<t199_lastCall+t199_interval){clearTimeout(t199_timeoutId);t199_timeoutId=setTimeout(function(){t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)},t199_interval-(t199_now-t199_lastCall))}else{t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)}})}
function t199_updateSectionsOffsets(sections){$(sections).each(function(){var t199_curSection=$(this);t199_curSection.attr('data-offset-top',t199_curSection.offset().top)})}
function t199_getSectionByHref(curlink){var t199_curLinkValue=curlink.attr('href').replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t199_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t199_curLinkValue.substring(1)+"']")}}
function t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId){var t199_scrollPosition=$(window).scrollTop(),t199_valueToReturn=t199_clickedSectionId;if(t199_sections.length!=0&&t199_clickedSectionId==null&&t199_sections[t199_sections.length-1].attr('data-offset-top')>t199_scrollPosition+300){t199_navLinks.removeClass('t-active');return null}
$(t199_sections).each(function(e){var t199_curSection=$(this),t199_sectionTop=t199_curSection.attr('data-offset-top'),t199_id=t199_curSection.attr('id'),t199_navLink=t199_sectionIdTonavigationLink[t199_id];if(t199_scrollPosition+300>=t199_sectionTop||(t199_sections[0].attr('id')==t199_id&&t199_scrollPosition>=$(document).height()-$(window).height())){if(t199_clickedSectionId==null&&!t199_navLink.hasClass('t-active')){t199_navLinks.removeClass('t-active');t199_navLink.addClass('t-active');t199_valueToReturn=null}else{if(t199_clickedSectionId!=null&&t199_id==t199_clickedSectionId){t199_valueToReturn=null}}
return!1}});return t199_valueToReturn}
function t688_unifyHeights(recid){if($(window).width()>=960){$('#rec'+recid+' .t688 .t-container .t688__row').each(function(){var t688_highestBox=0,t688_currow=$(this);$(':not(.t688__featured) .t688__inner-col',this).each(function(){var t688_curCol=$(this),t688_curText=t688_curCol.find(".t688__textwrapper_inner"),t688_curColHeight=t688_curText.outerHeight();if(t688_curColHeight>t688_highestBox){t688_highestBox=t688_curColHeight}});$('.t688__textwrapper',this).css('height',t688_highestBox);$('.t688__featured',this).css('height',$('.t688__col',this).height()+'px')})}else{$('.t688__textwrapper').css('height','auto');$("#rec"+recid).find(".t688__featured").css({'height':($("#rec"+recid).find(".t688__col").height()+'px')})}}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t702_showPopup(recid);t702_resizePopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t702_onSuccess(t702_form){var t702_inputsWrapper=t702_form.find('.t-form__inputsbox');var t702_inputsHeight=t702_inputsWrapper.height();var t702_inputsOffset=t702_inputsWrapper.offset().top;var t702_inputsBottom=t702_inputsHeight+t702_inputsOffset;var t702_targetOffset=t702_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t702_target=t702_targetOffset-200}else{var t702_target=t702_targetOffset-100}
if(t702_targetOffset>$(window).scrollTop()||($(document).height()-t702_inputsBottom)<($(window).height()-100)){t702_inputsWrapper.addClass('t702__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t702_target},400);setTimeout(function(){t702_inputsWrapper.addClass('t702__inputsbox_hidden')},400)}
var successurl=t702_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t702_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t702_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');el.find('.t-range').trigger('popupOpened');if(window.lazy=='y'){t_lazyload_update()}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t702_closePopup(recid)}});el.find('.t-popup__close').click(function(e){t702_closePopup(recid)});el.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recid);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t702_closePopup(recid)}})}
function t702_closePopup(recid){$('body').removeClass('t-body_popupshowed t702__body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t702_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t720_onSuccess(t720_form){var t720_inputsWrapper=t720_form.find('.t-form__inputsbox');var t720_inputsHeight=t720_inputsWrapper.height();var t720_inputsOffset=t720_inputsWrapper.offset().top;var t720_inputsBottom=t720_inputsHeight+t720_inputsOffset;var t720_targetOffset=t720_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t720_target=t720_targetOffset-200}else{var t720_target=t720_targetOffset-100}
if(t720_targetOffset>$(window).scrollTop()||($(document).height()-t720_inputsBottom)<($(window).height()-100)){t720_inputsWrapper.addClass('t720__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t720_target},400);setTimeout(function(){t720_inputsWrapper.addClass('t720__inputsbox_hidden')},400)}
var successurl=t720_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t720_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t772_init(recid){$('.t772__container_mobile-flex').bind('touchstart',function(){$('.t772__col').bind('touchmove',function(){if(typeof $(".t-records").attr('data-tilda-mode')=='undefined'){if(window.lazy=='y'){t_lazyload_update()}}})}).mouseup(function(){$('.t772__col').unbind('touchend')})}
function t774_init(recid){t774_unifyHeights(recid);$(window).bind('resize',t_throttle(function(){t774_unifyHeights(recid)},200));$(".t774").bind("displayChanged",function(){t774_unifyHeights(recid)});$(window).load(function(){t774_unifyHeights(recid)});setTimeout(function(){t774__updateLazyLoad(recid)},500)}
function t774__updateLazyLoad(recid){var scrollContainer=$("#rec"+recid+" .t774__container_mobile-flex");var curMode=$(".t-records").attr("data-tilda-mode");if(scrollContainer.length&&curMode!="edit"&&curMode!="preview"&&window.lazy==="y"){scrollContainer.bind('scroll',t_throttle(function(){t_lazyload_update()},500))}}
function t774_unifyHeights(recid){var t774_el=$('#rec'+recid),t774_blocksPerRow=t774_el.find(".t774__container").attr("data-blocks-per-row"),t774_cols=t774_el.find(".t774__content"),t774_mobScroll=t774_el.find(".t774__scroll-icon-wrapper").length;if($(window).width()<=480&&t774_mobScroll==0){t774_cols.css("height","auto");return}
var t774_perRow=+t774_blocksPerRow;if($(window).width()<=960&&t774_mobScroll>0){var t774_perRow=t774_cols.length}
else{if($(window).width()<=960){var t774_perRow=2}}
for(var i=0;i<t774_cols.length;i+=t774_perRow){var t774_maxHeight=0,t774_row=t774_cols.slice(i,i+t774_perRow);t774_row.each(function(){var t774_curText=$(this).find(".t774__textwrapper"),t774_curBtns=$(this).find(".t774__btn-wrapper, .t774__btntext-wrapper"),t774_itemHeight=t774_curText.outerHeight()+t774_curBtns.outerHeight();if(t774_itemHeight>t774_maxHeight){t774_maxHeight=t774_itemHeight}});t774_row.css("height",t774_maxHeight)}}
function t830_init(recid){var rec=$('#rec'+recid);var allrecords=$("#allrecords");var el=rec.find('.t830');var panel=rec.find('.t830__panel');var overlay=rec.find('.t830m__overlay');var menu=rec.find('.t830m');var submenu=rec.find('.t830m__submenu');var burger=rec.find('.t830__side .t830__burger');var menuItem=rec.find('.t830m__list-title a');var submenuItem=rec.find('.t830m__submenu-item a');if($(window).width()>1259){$('.t-body').prepend(rec);allrecords.addClass('t830__allrecords');$('.t-tildalabel').addClass('t830__t-tildalabel')}
t830_initMenu(rec,menu,burger);t830_removePadding(rec,allrecords);t830_calcCol(rec,menu,allrecords);t830_menuHighlight();t830_submenuHighlight();t830_openSubmenu(rec);t830_hoverShowMenu(rec,menu,panel,overlay,burger);$(window).resize(function(){t830_calcCol(rec,menu,allrecords);t830_removePadding(rec,allrecords);if(menu.hasClass('t830m_close')&&$(window).width()>1499){overlay.removeClass('t830m__menu_show')}});if(submenu.hasClass('t830m__submenu_close')){t830_toggleMenu(rec,submenu)}
if($(window).width()>1259){t830_scrollSideMenu(rec)}
menuItem.click(function(){if(window.location.hash.length!=0){menuItem.removeClass('t-active');$(this).addClass('t-active')}});submenuItem.click(function(){if(window.location.hash.length!=0){submenuItem.removeClass('t-active');$(this).addClass('t-active')}});t830_checkAnchorLinks(recid)}
function t830_calcCol(rec,menu,allrecords){if($(window).width()>1259&&!menu.hasClass('t830m_open')){allrecords.addClass('t830__allrecords_padd');$('.t-tildalabel').addClass('t830__t-tildalabel_padd')}
if($(window).width()>1259&&menu.hasClass('t830m_open')){allrecords.addClass('t830__allrecords_padd-small');$('.t-tildalabel').addClass('t830__t-tildalabel_padd-small')}}
function t830_toggleMenu(rec,submenu){var listTitle=rec.find('.t830m__list-title_toggle');var submenu;var textTitle;listTitle.click(function(){submenu=$(this).next();textTitle=$(this).find('.t830m__list-title-text');submenu.slideToggle('slow');textTitle.toggleClass('t830m__list-title-text_opacity');textTitle.toggleClass('t-menu__link-item')})}
function t830_openSubmenu(rec){var submenuItem=rec.find('.t830m__submenu-item a.t-active');submenuItem.parents('.t830m__submenu').css('display','block')}
function t830_hoverShowMenu(rec,menu,panel,overlay,burger){if($(window).width()>1259&&panel.hasClass('t830__panel_hover')){panel.mouseenter(function(e){menu.addClass('t830m__menu_show');burger.addClass('t830__burger_open');overlay.addClass('t830m__overlay_hover')});menu.mouseleave(function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open')});overlay.mouseenter(function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open');overlay.removeClass('t830m__overlay_hover')})
menu.find('a').on('click',function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open')});burger.click(function(){if(burger.hasClass('t830__burger_open')){t830_closeMenu(rec,menu);burger.removeClass('t830__burger_open')}else{menu.addClass('t830m__menu_show');burger.addClass('t830__burger_open');overlay.addClass('t830m__overlay_hover')}})}}
function t830_showMenu(rec,menu,burger){var panel=rec.find('.t830__panel');$('body').addClass('t830__body_menushowed');rec.find('.t830m').addClass('t830m__menu_show');rec.find('.t830m__overlay').addClass('t830m__menu_show');rec.find('.t830m__overlay, .t830m__close, a[href*=#]').click(function(){if($(this).is('.tooltipstered, .t794__tm-link')){return}
t830_closeMenu(rec,menu);burger.removeClass('t830__burger_open')});panel.addClass('t830__panel_close');$(document).keydown(function(e){if(e.keyCode==27){if($('.t-site-search-popup__background').length===0){$('body').removeClass('t830__body_menushowed');$('.t830m').removeClass('t830m__menu_show');burger.removeClass('t830__burger_open');$('.t830m__overlay').removeClass('t830m__menu_show')}}})}
function t830_closeMenu(rec,menu){var panel=rec.find('.t830__panel');if(menu.hasClass('t830m_open')&&$(window).width()<1500){panel.removeClass('t830__panel_close')}
$('body').removeClass('t830__body_menushowed');$('.t830m').removeClass('t830m__menu_show');$('.t830m__overlay').removeClass('t830m__menu_show')}
function t830_initMenu(rec,menu,burger){var obj=rec.find('.t830__menu__content');var panel=rec.find('.t830__panel');var menu=rec.find('.t830m');if(panel.hasClass('t830__panel_click')||(panel.hasClass('t830__panel_hover')&&$(window).width()<=1259)){obj.click(function(e){if(menu.hasClass('t830m__menu_show')){burger.removeClass('t830__burger_open');t830_closeMenu(rec,menu)}else{burger.addClass('t830__burger_open');t830_showMenu(rec,menu,burger)}
e.preventDefault()})}
$('.t830').bind('clickedAnchorInTooltipMenu',function(){t830_closeMenu(rec,menu)})}
function t830_menuHighlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$(".t830m__list-title a[href='"+url+"']").addClass('t-active');$(".t830m__list-title a[href='"+url+"/']").addClass('t-active');$(".t830m__list-title a[href='"+pathname+"']").addClass('t-active');$(".t830m__list-title a[href='/"+pathname+"']").addClass('t-active');$(".t830m__list-title a[href='"+pathname+"/']").addClass('t-active');$(".t830m__list-title a[href='/"+pathname+"/']").addClass('t-active')}
function t830_submenuHighlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname="/"}
$(".t830m__submenu-item a[href='"+url+"']").addClass('t-active');$(".t830m__submenu-item a[href='"+url+"/']").addClass('t-active');$(".t830m__submenu-item a[href='"+pathname+"']").addClass('t-active');$(".t830m__submenu-item a[href='/"+pathname+"']").addClass('t-active');$(".t830m__submenu-item a[href='"+pathname+"/']").addClass('t-active');$(".t830m__submenu-item a[href='/"+pathname+"/']").addClass('t-active')}
function t830_scrollSideMenu(rec){var container=rec.find('.t830m__container');container.on('scroll wheel DOMMouseScroll mousewheel',function(e){var searchResultContainer=rec.find('.t-site-search-dm');if(searchResultContainer.length==0){t830_stopScroll(this,e)}})}
function t830_stopScroll(block,eventScroll){var $this=$(block);var scrollTop=block.scrollTop;var scrollHeight=block.scrollHeight;var height=$this.height();var delta=(eventScroll.type=='DOMMouseScroll'?eventScroll.originalEvent.detail*-40:eventScroll.originalEvent.wheelDelta);var up=delta>0;var prevent=function(){eventScroll.stopPropagation();eventScroll.preventDefault();eventScroll.returnValue=!1;return!1}
if(!up&&-delta>scrollHeight-height-scrollTop){$this.scrollTop(scrollHeight);return prevent()}else if(up&&delta>scrollTop){$this.scrollTop(0);return prevent()}}
function t830_removePadding(rec,allrecords){if(rec.css('display')=='none'){allrecords.css('padding-left',0);$('.t-tildalabel').css('padding-left',0)}}
function t830_checkAnchorLinks(recid){if($(window).width()>=960){var submenuNavLinks=$("#rec"+recid+" .t830m__list a:not(.tooltipstered)[href*='#']");if(submenuNavLinks.length>0){setTimeout(function(){t830_catchScroll(submenuNavLinks,recid)},500)}}}
function t830_catchScroll(navLinks,recid){var rec=$('#rec'+recid);var clickedSectionId=null;var sections=new Array();var sectionIdTonavigationLink=[];var interval=100;var lastCall;var timeoutId;var navLinks=$(navLinks.get().reverse());navLinks.each(function(){var cursection=t830_getSectionByHref($(this));if(typeof cursection.attr('id')!='undefined'){sections.push(cursection)}
sectionIdTonavigationLink[cursection.attr('id')]=$(this)});t830_updateSectionsOffsets(sections);sections.sort(function(a,b){return b.attr('data-offset-top')-a.attr('data-offset-top')});$(window).bind('resize',t_throttle(function(){t830_updateSectionsOffsets(sections)},200));$('.t830').bind('displayChanged',function(){t830_updateSectionsOffsets(sections)});setInterval(function(){t830_updateSectionsOffsets(sections)},5000);t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId);navLinks.click(function(){var clickedSection=t830_getSectionByHref($(this));if(!$(this).hasClass('tooltipstered')&&typeof clickedSection.attr('id')!='undefined'){navLinks.removeClass('t-active');$(this).addClass('t-active');clickedSectionId=t830_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var now=new Date().getTime();if(lastCall&&now<(lastCall+interval)){clearTimeout(timeoutId);timeoutId=setTimeout(function(){lastCall=now;clickedSectionId=t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId)},interval-(now-lastCall))}else{lastCall=now;clickedSectionId=t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId)}})}
function t830_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'');if(curLinkValue[0]=='/'){curLinkValue=curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue.substring(1)+"']")}}
function t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId){var scrollPosition=$(window).scrollTop();var valueToReturn=clickedSectionId;if(sections.length!=0&&clickedSectionId==null&&sections[sections.length-1].attr('data-offset-top')>(scrollPosition+300)){navLinks.removeClass('t-active');return null}
$(sections).each(function(e){var curSection=$(this);var sectionTop=curSection.attr('data-offset-top');var id=curSection.attr('id');var navLink=sectionIdTonavigationLink[id];if(((scrollPosition+300)>=sectionTop)||(sections[0].attr("id")==id&&scrollPosition>=$(document).height()-$(window).height())){if(clickedSectionId==null&&!navLink.hasClass('t-active')){navLinks.removeClass('t-active');navLink.addClass('t-active');valueToReturn=null}else{if(clickedSectionId!=null&&id==clickedSectionId){valueToReturn=null}}
return!1}});return valueToReturn}
function t830_updateSectionsOffsets(sections){$(sections).each(function(){var curSection=$(this);curSection.attr('data-offset-top',curSection.offset().top)})}
function t923_init(recid){t923_unifyHeights(recid);t_slds_updateSlider(recid);$(window).bind('resize',t_throttle(function(){t923_unifyHeights(recid)},200));$(".t923").bind("displayChanged",function(){setTimeout(function(){t923_unifyHeights(recid);t_slds_updateSlider(recid)})});$(window).load(function(){t923_unifyHeights(recid)})}
function t923_unifyHeights(recid){var t923_el=$('#rec'+recid),t923_cols=t923_el.find(".t923__content");var t923_maxHeight=0;t923_cols.each(function(){var t923_curText=$(this).find(".t923__textwrapper"),t923_curBtns=$(this).find(".t923__btn-wrapper, .t923__btntext-wrapper"),t923_itemHeight=t923_curText.outerHeight()+t923_curBtns.outerHeight();if(t923_itemHeight>t923_maxHeight){t923_maxHeight=t923_itemHeight}});t923_cols.css("height",t923_maxHeight)}